In [5]:
import numpy as np

In [6]:
a = np.arange(1, 11)
print(a)
print(sum(a))
mul = 1
for i in a:
    mul *= i
print(mul)


[ 1  2  3  4  5  6  7  8  9 10]
55
3628800


In [4]:
a = np.arange(0, 21)
print(a)
print(a[3 : 8])
# if we want 8th index we can do a[3: 9]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[3 4 5 6 7]


In [15]:
A = np.arange(25).reshape(5, 5)
print(A)
print(A[:2, -2:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[3 4]
 [8 9]]


In [18]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 4, 6, 8])
print(a + b)
print(a * b)
for i in b:
    print(np.sin(i))

[ 3  6  9 12]
[ 2  8 18 32]
0.9092974268256817
-0.7568024953079282
-0.27941549819892586
0.9893582466233818


In [22]:
a = np.random.randint(0, 50, size=20)
result = a[(a < 25) & (a < 40)]
print(result)


[19 18  4 12 12 15 23 24  2 15 24]


In [27]:
A = np.arange(25).reshape(5, 5)

np.fill_diagonal(A, 0)
print(A)

A = np.where(A != 0, A * 2, A)

print(A)

# or we can just multiply matrix by 2 so the diagonal elements will stay the same :DD

[[ 0  1  2  3  4]
 [ 5  0  7  8  9]
 [10 11  0 13 14]
 [15 16 17  0 19]
 [20 21 22 23  0]]
[[ 0  2  4  6  8]
 [10  0 14 16 18]
 [20 22  0 26 28]
 [30 32 34  0 38]
 [40 42 44 46  0]]


In [33]:
a = np.arange(1, 10).reshape(3, 3)
print(a)
print(a[1, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5]


In [38]:
A = np.arange(6).reshape(2, 3)
print(A)

print(A.transpose()) # we can use built in function to do that :0

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [40]:
A = np.arange(9).reshape(3, 3)
b = np.arange(3, 6)

print(A)
print(b)
print(A + b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4 5]
[[ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [45]:
A = np.arange(16).reshape(4, 4)
print(A)

rows = [0, 2, 3]
cols = [1, 3, 2]

print(A[rows, cols])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1 11 14]
