In [1]:
import numpy as np

In [2]:
l1 = [1, 2, 3, 4]
l2 = [1, 2, 3, 4]
print(l1 + l2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [12]:
l1 = np.array([1, 2, 3, 4, 5])
l2 = np.array([1, 2, 3, 4, 5])
print(l1 + l2)


[ 2  4  6  8 10]


In [14]:
a = np.arange(25).reshape(5, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [17]:
red_slice = a[:, 1::2]
print(red_slice)

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]]


In [19]:
blue_slice = a[1::2, [0, 2]]
print(blue_slice)

[[ 5  7]
 [15 17]]


In [20]:
a = np.array([10, 20, 30, 40, 50])
indices = [1, 3, -1]
result = a[indices]
print(result)

[20 40 50]


In [24]:
# Indexing with booleans
b = np.array([1, 0, 1, 1, 0], dtype=set)
print(b)

[1 0 1 1 0]


In [29]:
A = np.arange(25).reshape(5, 5)
print(A)
print("================")
blue_elements = np.diagonal(A, offset=-1)
print(blue_elements)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 5 11 17 23]


In [31]:
print(A[(A % 3 == 0)])

[ 0  3  6  9 12 15 18 21 24]
