In [1]:
import numpy as np

In [3]:
x = np.arange(0, 2 * np.pi, 0.1)
print(x[:5])

[0.  0.1 0.2 0.3 0.4]


In [5]:
c = (2 * np.pi / 10)
print(c)



0.6283185307179586


In [12]:
# Functions
y = np.sin(np.pi / 6)
print(y)

0.49999999999999994


In [30]:
a = np.array([1, 2, 3])
a[0] = 110.9
print(a)
# adding a float to an int list takes that float and turn it into int using (floor rounding)

[110   2   3]


In [31]:
a.fill(-5.8)
print(a)

[-5 -5 -5]


In [35]:
a = np.array([
    [0, 1, 2, 3],
    [10, 11, 12, 13]
])

print(a)

print(a[1, 3])

[[ 0  1  2  3]
 [10 11 12 13]]
13


In [40]:
a = np.array([11, 13, 15, 17, 19])
a[-2:] = 99999
print(a)



[   11    13    15 99999 99999]


In [46]:
a = np.arange(25).reshape(5, 5)
print(a)

print(a[4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[20 21 22 23 24]


In [48]:
# now output the second and 4th col
print(a[:, 1::2])

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]]


In [52]:
# now about blue ones
print(a[1::2, [0, 2]])

[[ 5  7]
 [15 17]]


In [59]:
a = np.arange(20, 45).reshape(5, 5)
print(a)
print(a[(a % 3 == 0)])

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]
[21 24 27 30 33 36 39 42]


In [63]:
a = np.array([0, 1, 2, 3, 5], dtype='uint8')
print(a.dtype)

uint8
